name: brana_mobile
description: Brana Mobile.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  google_fonts: ^5.1.0
  flutter_svg: ^1.0.0
  # audioplayers: ^5.1.0
  # audioplayers_linux: ^3.0.0
  # audioplayers_android: ^4.0.1
  # audioplayers_darwin: ^5.0.1
  audioplayers_platform_interface: ^6.0.0
  anim_search_bar: ^2.0.3
  cached_network_image: ^3.2.3
  line_icons: ^2.0.3 
  flutter_staggered_animations:
  flutter_neumorphic:

  file: ^6.0.0
  meta: ^1.9.1
  path_provider: ^2.1.1
  synchronized: ^3.1.0
  uuid: ^3.0.7

  audio_video_progress_bar: ^2.0.0
  just_audio: ^0.9.34
  mpv_dart: ^0.0.1
  just_audio_mpv: ^0.1.7
  animate_do: ^3.0.2
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  audio_service: ^0.18.11
  connectivity_plus: ^5.0.1
  carousel_slider:
  http: ^1.1.0
  shared_preferences_windows: ^2.2.0 
  email_validator:
  image_picker:
  string_validator:
  path:
  intl:
  logger: ^2.0.2
  just_audio_background: ^0.0.1-beta.10
  flutter_cache_manager: ^3.3.1
  another_transformer_page_view: ^2.0.1
  smooth_page_indicator:
  device_preview: ^1.1.0
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/authors/
    - assets/books/
    - assets/images/
    - assets/audiobooks/
    # - assets/images/image2.png
    - assets/audiobooks/GetachewKassa.mp3
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages